

// 用户相关
export const RECEIVE_USERINFO = 'RECEIVE_USERINFO'
export const UPDATE_USERNAME = 'UPDATE_USERNAME'
export const SUCCESS_LOGIN = 'SUCCESS_LOGIN'
export const SUCCESS_LOGOUT = 'SUCCESS_LOGOUT'

export const RECEIVE_DEVICEINFO = 'RECEIVE_DEVICEINFO'
export const RECEIVE_LOCALINFO = 'RECEIVE_LOCALINFO'
export const RECEIVE_CONTACTS = 'RECEIVE_CONTACTS'


// export const RECEIVE_PROJECTS = 'RECEIVE_PROJECTS'
// export const FAILURE_PROJECTS = 'FAILURE_PROJECTS'
// export const UPDATE_PRODUCT = 'UPDATE_PRODUCT'
// export const UPDATE_COUNTDOWN_PRODUCTS = 'UPDATE_COUNTDOWN_PRODUCTS'
// export const RECEIVE_PROJECTDETAIL = 'RECEIVE_PROJECTDETAIL'
// export const FAILURE_PROJECTDETAIL = 'FAILURE_PROJECTDETAIL'
// export const UPDATE_DETAIL= 'UPDATE_DETAIL'


export const UPDATE_AJAX = 'UPDATE_AJAX'
export const SHOW_MSG = 'SHOW_MSG'
export const HIDE_MSG = 'HIDE_MSG'
export const SHOW_MODAL = 'SHOW_MODAL'
export const HIDE_MODAL = 'HIDE_MODAL'
export const CHANGE_NAV = 'CHANGE_NAV'
export const SHOW_NAV = 'SHOW_NAV'
export const HIDE_NAV = 'HIDE_NAV'


// 页面切换
export const UPDATE_DIRECTION = 'UPDATE_DIRECTION'
export const UPDATE_TRANSITION = 'UPDATE_TRANSITION'

